version: "3.8"

services:
  app:
    build:
      context: .
    user: "$UID:$GID"
    restart: always
    tty: true
    volumes:
      - ./src:/app
    environment:
      - WATCHPACK_POLLING=true
    command: ["bash", "-c", "npm run dev"]
    ports:
      - "3000:3000"
