services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: next-app
    ports:
      - "3333:3000"
    env_file:
      - ./.env
    volumes:
      - ./:/app/src
      - ./public:/app/public
      - node_modules:/app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    restart: always
    tty: true
    stdin_open: true

volumes:
  node_modules:
